Prep data

In [15]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

PART A

A1

In [16]:
df_2019_raw = pd.read_excel("Bieu 1A.00&Suy rong B_DN 2019.xlsx")

vsic = pd.read_excel("VSIC 2007.xls")

In [17]:
#Check data
print("Shape of 2019 data:", df_2019_raw.shape)

print("Columns in 2019 data:", df_2019_raw.columns.tolist())

display(df_2019_raw.head())

df_2019_raw.info()

Shape of 2019 data: (689251, 156)
Columns in 2019 data: ['NamSL', 'LoaiPhieu_Dieutra', 'MaTinh_Dieutra', 'MaHuyen_Dieutra', 'MaXa_Dieutra', 'DN_MaTinh', 'DN_MaHuyen', 'DN_MaXa', 'Masothue', 'Masothue2', 'TenDN', 'Diachi', 'Dienthoai', 'Fax', 'Email', 'LoaihinhKT', 'LoaihinhKT2', 'Tyle_Von_NNTW', 'Tyle_Von_NNDP', 'Tyle_Von_NN', 'Nhanuoc_CoChiphoi', 'Tyle_Von_Nuocngoai', 'CoMua_HHDV_Nuocngoai', 'Tongtien_Tra_Nuocngoai', 'CoBan_HHDV_Nuocngoai', 'Tongtien_Thu_Nuocngoai', 'SoLaodong_DauNam', 'SoLaodong_DauNam_Nu', 'SoLaodong_CuoiNam', 'SoLaodong_Cuoinam_Nganh', 'SoLaodong_CuoiNam_Nu', 'SoLaodong_BQ', 'SoLaodong_BHXH', 'SoLaodong_KhongLuong', 'SoLaodong_Nuocngoai', 'Tongtien_Tra_NguoiLD', 'Tongtien_BHXH_Tra', 'Tongtien_Donggop', 'TonDauNam', 'TonDauNam_CN', 'TonDauNam_CN_Dodang', 'TonDauNam_CN_Thanhpham', 'TonDauNam_CN_GuiBan', 'TonCuoiNam', 'TonCuoiNam_CN', 'TonCuoiNam_CN_Dodang', 'TonCuoiNam_CN_Thanhpham', 'TonCuoiNam_CN_GuiBan', 'TongDoanhthu_DTDN', 'MaNganhSXKD_Chinh', 'Doanhthu_Nganh', 'Co_Vondautu', 'Co_GiacongLaprap', 'VonDieuLe_Tongso', 'GopVonDieuLe_Tongso', 'GopVonDieuLeLuyke_Tongso', 'VonDieuLe_VietNam', 'GopVonDieuLe_VietNam', 'GopVonDieuLeLuyke_VietNam', 'VonDieuLe_NhaNuoc', 'GopVonDieuLe_NhaNuoc', 'GopVonDieuLeLuyke_NhaNuoc', 'VonDieuLe_NgoaiNhaNuoc', 'GopVonDieuLe_NgoaiNhaNuoc', 'GopVonDieuLeLuyke_NgoaiNhaNuoc', 'VonDieuLe_Khac', 'GopVonDieuLe_Khac', 'GopVonDieuLeLuyke_Khac', 'VonDieuLe_NuocNgoai', 'GopVonDieuLe_NuocNgoai', 'GopVonDieuLeLuyke_NuocNgoai', 'TinhtrangHD', 'TongVondautu', 'Co_BCTC', 'DKThue_TTHD', 'DKThue_NamBD', 'LaDoituongChonMau1A', 'MaNganhC4', 'Khuvuc', 'NhomLaodong', 'Taisan_Tong_DK', 'Taisan_Tong_CK', 'Taisan_NH_DK', 'Taisan_NH_CK', 'Tonkho_DK', 'Tonkho_CK', 'Taisan_DH_DK', 'Taisan_DH_CK', 'TSCD_Nguyengia_DK', 'TSCD_Nguyengia_CK', 'TSCD_HMLK_DK', 'TSCD_HMLK_CK', 'TSCD_Huuhinh_DK', 'TSCD_Huuhinh_CK', 'TSCD_ThueTC_DK', 'TSCD_ThueTC_CK', 'TSCD_Vohinh_DK', 'TSCD_Vohinh_CK', 'TSCD_Huuhinh_Nguyengia_DK', 'TSCD_Huuhinh_Nguyengia_CK', 'TSCD_ThueTC_Nguyengia_DK', 'TSCD_ThueTC_Nguyengia_CK', 'TSCD_Vohinh_Nguyengia_DK', 'TSCD_Vohinh_Nguyengia_CK', 'TSCD_Huuhinh_HMLK_DK', 'TSCD_Huuhinh_HMLK_CK', 'TSCD_ThueTC_HMLK_DK', 'TSCD_ThueTC_HMLK_CK', 'TSCD_Vohinh_HMLK_DK', 'TSCD_Vohinh_HMLK_CK', 'Chiphi_XDCB_Dodang_DK', 'Chiphi_XDCB_Dodang_CK', 'Nguonvon_Tong_DK', 'Nguonvon_Tong_CK', 'Von_ChuSohuu_DK', 'Von_ChuSohuu_CK', 'Doanhthu_BH_CCDV', 'Giamtru_Doanhthu', 'Doanhthu_Thuan_BH_CCDV', 'Gia_VonHangban', 'Doanhthu_HDTC', 'Thunhap_Khac', 'Loinhuan_TruocThue', 'Chiphi_Thue_TNDN', 'TSCD_DK', 'TSCD_CK', 'NoPhaitra_DK', 'NoPhaitra_CK', 'ChiThueHL', 'LoinhuanGop', 'Chi_TC', 'Chi_TC_LV', 'Chi_BHang', 'Chi_QLDN', 'Loinhuan_Thuan', 'Chi_Khac', 'Loinhuan_Khac', 'Loinhuan_SauThue', 'Lai_CPhieu', 'Tien', 'DautuTC_NH', 'PhaiThu_NH', 'PhaiThu_NH_KH', 'Tratruoc_NBan_NH', 'BDS_Dautu', 'BDS_Dautu_NGia', 'BDS_Dautu_HMLK', 'Taisan_DH_Khac', 'Phaitra_NBan_NH', 'NMua_Tratruoc_NH', 'Thue', 'PhaiTra_NguoiLD', 'VayNoTC_NH', 'DP_Phaitra_NH', 'VonGop_ChuSH', 'LoinhuanST_ChuaPP']

,NamSL,LoaiPhieu_Dieutra,MaTinh_Dieutra,MaHuyen_Dieutra,MaXa_Dieutra,DN_MaTinh,DN_MaHuyen,DN_MaXa,Masothue,Masothue2,TenDN,Diachi,Dienthoai,Fax,Email,LoaihinhKT,LoaihinhKT2,Tyle_Von_NNTW,Tyle_Von_NNDP,Tyle_Von_NN,Nhanuoc_CoChiphoi,Tyle_Von_Nuocngoai,CoMua_HHDV_Nuocngoai,Tongtien_Tra_Nuocngoai,CoBan_HHDV_Nuocngoai,Tongtien_Thu_Nuocngoai,SoLaodong_DauNam,SoLaodong_DauNam_Nu,SoLaodong_CuoiNam,SoLaodong_Cuoinam_Nganh,SoLaodong_CuoiNam_Nu,SoLaodong_BQ,SoLaodong_BHXH,SoLaodong_KhongLuong,SoLaodong_Nuocngoai,Tongtien_Tra_NguoiLD,Tongtien_BHXH_Tra,Tongtien_Donggop,TonDauNam,TonDauNam_CN,TonDauNam_CN_Dodang,TonDauNam_CN_Thanhpham,TonDauNam_CN_GuiBan,TonCuoiNam,TonCuoiNam_CN,TonCuoiNam_CN_Dodang,TonCuoiNam_CN_Thanhpham,TonCuoiNam_CN_GuiBan,TongDoanhthu_DTDN,MaNganhSXKD_Chinh,Doanhthu_Nganh,Co_Vondautu,Co_GiacongLaprap,VonDieuLe_Tongso,GopVonDieuLe_Tongso,GopVonDieuLeLuyke_Tongso,VonDieuLe_VietNam,GopVonDieuLe_VietNam,GopVonDieuLeLuyke_VietNam,VonDieuLe_NhaNuoc,GopVonDieuLe_NhaNuoc,GopVonDieuLeLuyke_NhaNuoc,VonDieuLe_NgoaiNhaNuoc,GopVonDieuLe_NgoaiNhaNuoc,GopVonDieuLeLuyke_NgoaiNhaNuoc,VonDieuLe_Khac,GopVonDieuLe_Khac,GopVonDieuLeLuyke_Khac,VonDieuLe_NuocNgoai,GopVonDieuLe_NuocNgoai,GopVonDieuLeLuyke_NuocNgoai,TinhtrangHD,TongVondautu,Co_BCTC,DKThue_TTHD,DKThue_NamBD,LaDoituongChonMau1A,MaNganhC4,Khuvuc,NhomLaodong,Taisan_Tong_DK,Taisan_Tong_CK,Taisan_NH_DK,Taisan_NH_CK,Tonkho_DK,Tonkho_CK,Taisan_DH_DK,Taisan_DH_CK,TSCD_Nguyengia_DK,TSCD_Nguyengia_CK,TSCD_HMLK_DK,TSCD_HMLK_CK,TSCD_Huuhinh_DK,TSCD_Huuhinh_CK,TSCD_ThueTC_DK,TSCD_ThueTC_CK,TSCD_Vohinh_DK,TSCD_Vohinh_CK,TSCD_Huuhinh_Nguyengia_DK,TSCD_Huuhinh_Nguyengia_CK,TSCD_ThueTC_Nguyengia_DK,TSCD_ThueTC_Nguyengia_CK,TSCD_Vohinh_Nguyengia_DK,TSCD_Vohinh_Nguyengia_CK,TSCD_Huuhinh_HMLK_DK,TSCD_Huuhinh_HMLK_CK,TSCD_ThueTC_HMLK_DK,TSCD_ThueTC_HMLK_CK,TSCD_Vohinh_HMLK_DK,TSCD_Vohinh_HMLK_CK,Chiphi_XDCB_Dodang_DK,Chiphi_XDCB_Dodang_CK,Nguonvon_Tong_DK,Nguonvon_Tong_CK,Von_ChuSohuu_DK,Von_ChuSohuu_CK,Doanhthu_BH_CCDV,Giamtru_Doanhthu,Doanhthu_Thuan_BH_CCDV,Gia_VonHangban,Doanhthu_HDTC,Thunhap_Khac,Loinhuan_TruocThue,Chiphi_Thue_TNDN,TSCD_DK,TSCD_CK,NoPhaitra_DK,NoPhaitra_CK,ChiThueHL,LoinhuanGop,Chi_TC,Chi_TC_LV,Chi_BHang,Chi_QLDN,Loinhuan_Thuan,Chi_Khac,Loinhuan_Khac,Loinhuan_SauThue,Lai_CPhieu,Tien,DautuTC_NH,PhaiThu_NH,PhaiThu_NH_KH,Tratruoc_NBan_NH,BDS_Dautu,BDS_Dautu_NGia,BDS_Dautu_HMLK,Taisan_DH_Khac,Phaitra_NBan_NH,NMua_Tratruoc_NH,Thue,PhaiTra_NguoiLD,VayNoTC_NH,DP_Phaitra_NH,VonGop_ChuSH,LoinhuanST_ChuaPP
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020.00,A,1.00,1.00,1.00,1.00,1.00,1.00,100512361.00,NaN,CÔNG TY TRÁCH NHIỆM HỮU HẠN THƯƠNG MẠI VÀ BAO ...,"Số 12 , Ngõ 66 , Phố Nghĩa Dũng",02436444187,NaN,ketoanqa@gmail.com,8.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,861.00,2.00,NaN,31.00,13.00,30.00,30.00,12.00,31.00,28.00,0.00,0.00,2243.00,0.00,491.00,23110.00,23110.00,23.00,9.00,0.00,30090.00,30090.00,31.00,23.00,0.00,59577.00,22201.00,59577.00,1.00,2.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,1.00,1995-06-03 00:00:00,1.00,2220.00,1.00,2.00,48333.80,53689.80,36457.20,42226.20,23109.60,30090.40,11876.60,11463.60,0.00,0.00,0.00,0.00,11876.60,11463.60,0.00,0.00,0.00,0.00,33699.70,34904.30,0.00,0.00,0.00,0.00,21823.10,23440.70,0.00,0.00,0.00,0.00,0.00,0.00,48333.80,53689.80,11513.40,11660.80,NaN,NaN,59577.00,55911.30,1.60,110.50,187.70,37.50,11876.60,11463.60,36820.40,42029.00,NaN,3665.70,1615.50,1615.50,500.60,1404.70,146.50,69.30,41.20,150.20,NaN,1995.60,0.00,9554.90,8777.40,777.60,0.00,0.00,0.00,0.00,3303.80,101.10,19.60,0.00,38604.50,0.00,0.00,1810.80
2,2020.00,A,1.00,1.00,1.00,1.00,1.00,1.00,100998568.00,NaN,CÔNG TY TRÁCH NHIỆM HỮU HẠN TÂN HÀ SÁNG,"Số 49 Ngõ 33 Phố Tân Ấp, P. Phúc Xá, Q. Ba Đìn...",02437164399,NaN,ketoanhasa@gmail.com,8.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,2.00,NaN,60.00,35.00,66.00,56.00,41.00,65.00,66.00,0.00,0.00,3241.00,0.00,1102.00,27446.00,10982.00,0.00,10982.00,NaN,18300.00,4570.00,0.00,4570.00,NaN,58413.00,14100.00,8737.00,1.00,2.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,1.00,2000-06-01 00:00:00,1.00,1410.00,1.00,3.00,56194.60,30555.10,53434.10,28413.10,27445.90,18299.80,2760.50,2142.00,5348.40,4640.40,2901.70,2725.20,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,56194.60,30555.10,9733.60,5899.00,NaN,NaN,58413.00,56069.70,2.70,2224.10,-3766.30,0.00,2446.70,1915.30,46461.00,24656.10,NaN,2343.70,2769.90,2769.90,0.00,3945.80,-4369.40,1621.00,603.10,-3766.30,NaN,587.80,0.00,9525.50,8339.30,963.20,0.00,0.00,0.00,226.70,5355.00,22.70,715.90,0.00,18540.90,0.00,15680.00,-9781.00
3,2020.00,A,1.00,1.00,1.00,1.00,1.00,1.00,101063863.00,NaN,CÔNG TY TRÁCH NHIỆM HỮU HẠN HAI CHI,Số 21 ngõ 140 phố Nghĩa Dũng,0912361816,NaN,haichi.vn@gmail.com,8.00,NaN,NaN,NaN,0.00,NaN,NaN,2.00,NaN,1.00,48.00,8.00,6.00,7.00,7.00,5.00,7.00,0.00,0.00,0.00,534.00,0.00,0.00,249.00,249.00,0.00,249.00,0.00,9.00,9.00,0.00,9.00,0.00,1873.00,13920.00,1873.00,2.00,2.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,1.00,1999-11-09 00:00:00,1.00,1392.00,1.00,1.00,1552.30,1143.70,596.40,151.00,248.50,8.50,955.90,992.70,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1552.30,1143.70,710.80,716.10,NaN,NaN,1873.00,983.90,0.00,0.00,5.40,1.10,0.00,0.00,841.50,427.60,NaN,888.90,0.00,0.00,0.00,883.40,5.40,0.00,0.00,4.40,NaN,142.50,0.00,0.10,0.10,0.00,0.00,0.00,0.00,992.70,22.20,405.40,0.00,0.00,0.00,0.00,600.00,116.20
4,2020.00,A,1.00,1.00,1.00,1.00,1.00,1.00,101070772.00,NaN,DOANH NGHIỆP TƯ NHÂN NHÂN SẢN XUẤT VÀ THƯƠNG M...,"Số 53, Ngõ 15 đường Hồng Hà, P. Phúc Xá, Q.Ba ...",0983281088,NaN,ktth@tamadong.com,6.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,2.00,NaN,5.00,3.00,5.00,4.00,3.00,5.00,0.00,0.00,0.00,435.00,0.00,0.00,742.00,742.00,626.00,45.00,0.00,810.00,810.00,657.00,44.00,0.00,1436.00,16292.00,1149.00,1.00,2.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,1.00,2000-11-21 00:00:00,1.00,1629.00,1.00,1.00,3297.10,4900.40,2146.70,3361.40,741.80,810.10,1150.40,1539.00,2671.10,3443.90,1651.40,1909.80,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3297.10,4900.40,-882.20,-869.70,NaN,NaN,1436.00,1268.50,0.00,272.70,15.50,3.10,1019.80,1534.00,4179.30,5770.10,NaN,168.00,5.50,0.00,0.00,419.70,-257.20,0.00,272.70,12.40,NaN,143.70,0.00,2407.50,2177.20,149.20,0.00,0.00,0.00,5.00,1666.20,0.00,3.50,0.00,121.80,0.00,1994.10,-2863.80

<class 'pandas.DataFrame'>
RangeIndex: 689251 entries, 0 to 689250
Columns: 156 entries, NamSL to LoinhuanST_ChuaPP
dtypes: float64(149), object(3), str(4)
memory usage: 820.3+ MB

In [ ]:
revenue_col = df_2019_raw['TongDoanhthu_DTDN']

subset_iloc = df_2019_raw.iloc[0:5, 0:3]

subset_loc = df_2019_raw.loc[0:4, ['Masothue', 'TenDN']]

A2. Harmonize variables across years

In [ ]:
df_2019 = df_2019_raw.copy()

core_cols = [
    'Masothue', 'TenDN', 'LoaihinhKT', 'MaNganhSXKD_Chinh', 'MaTinh_Dieutra', 
    'TongDoanhthu_DTDN', 'Loinhuan_SauThue', 'SoLaodong_CuoiNam', 'SoLaodong_BQ'
]

df_2019 = df_2019[core_cols]

df_2019['Year'] = 2019

PART B

B1

In [ ]:
missing_report = pd.DataFrame({
    'Missing_Count': df_2019.isnull().sum(),
    'Missing_Percentage': (df_2019.isnull().sum() / len(df_2019)) * 100,
    'Data_Type': df_2019.dtypes
})

missing_report = missing_report.sort_values(by='Missing_Percentage', ascending=False)
display(missing_report)

                   Missing_Count  Missing_Percentage Data_Type
TongDoanhthu_DTDN         571384               82.90   float64
SoLaodong_BQ                 869                0.13   float64
Loinhuan_SauThue               2                0.00   float64
Masothue                       1                0.00   float64
TenDN                          1                0.00    object
LoaihinhKT                     1                0.00   float64
MaNganhSXKD_Chinh              1                0.00   float64
MaTinh_Dieutra                 1                0.00   float64
SoLaodong_CuoiNam              1                0.00   float64
Year                           0                0.00     int64

"\nNhận xét và Quyết định (bạn tự viết dựa trên kết quả hiển thị ra):\n- Các biến có % missing cao nhất là gì? (Ví dụ: SoLaodong_BQ thiếu 20%)\n- Quyết định (Decision): \n  + Không tự động dùng fillna(0).\n  + Đối với 'Masothue' (Key ID): Nếu bị null thì nên drop vì không xác định được doanh nghiệp (df_2019.dropna(subset=['Masothue'])).\n  + Đối với categorical (ngành, tỉnh): Có thể điền 'Unknown' thay vì xoá.\n  + Đối với numerical (doanh thu, lợi nhuận): Có thể giữ nguyên (NaN), khi tính mean/median pandas sẽ tự động bỏ qua NaN, thay vì fill 0 làm méo mó kết quả phân tích.\n"

B2

In [ ]:
exact_duplicates = df_2019.duplicated().sum()
print(f"Exact duplicates count: {exact_duplicates}")

mst_duplicates = df_2019.duplicated(subset=['Masothue']).sum()
print(f"Duplicated Tax IDs count: {mst_duplicates}")

display(df_2019[df_2019.duplicated(subset=['Masothue'], keep=False)].sort_values('Masothue').head(10))

df_2019 = df_2019.drop_duplicates()

df_2019['Masothue'] = df_2019['Masothue'].astype(str).str.strip()
df_2019['Masothue'] = df_2019['Masothue'].str.replace(r'\.0$', '', regex=True)

Exact duplicates count: 0
Duplicated Tax IDs count: 399

,Masothue,TenDN,LoaihinhKT,MaNganhSXKD_Chinh,MaTinh_Dieutra,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ,Year
27861,100100015.00,CÔNG TY THAN KHÁNH HOÀ - VVMI,4.00,5100.00,19.00,854319.00,0.00,752.00,756.00,2019
13152,100100015.00,TỔNG C.TY CÔNG NGHIỆP MỎ VIỆT BẮC-VINACOMIN,3.00,5100.00,1.00,2404261.00,263970.60,1997.00,2016.00,2019
27562,100100015.00,CÔNG TY THAN NÚI HỐNG VVMI,4.00,5100.00,19.00,932633.00,0.00,604.00,607.00,2019
1918,100100417.00,TỔNG C.TY ĐIỆN LỰC MIỀN BẮC,1.00,35122.00,1.00,120611977.00,410140.00,21167.00,21202.00,2019
14501,100100417.00,CÔNG TY CỔ PHẦN CƠ ĐIỆN VẬT TƯ,9.00,27320.00,1.00,44434.00,449.30,50.00,50.00,2019
43368,100100417.00,CÔNG TY ĐIỆN LỰC THÁI BÌNH,4.00,33140.00,34.00,14482.60,288.20,95.00,95.00,2019
13153,100100689.00,CÔNG TY CỔ PHẦN KINH DOANH THAN MIỀN BẮC - VIN...,9.00,46611.00,1.00,10857337.00,0.00,655.00,655.00,2019
51159,100100689.00,CHI NHÁNH CÔNG TY CỔ PHẦN KINH DOANH THAN MIỀN...,3.00,46611.00,40.00,54870.10,0.00,47.00,47.00,2019
52572,100100826.00,CHI NHÁNH CÔNG TY CỔ PHẦN DỆT MAY HÀ NỘI,9.00,14100.00,40.00,109990.00,0.00,1206.00,1189.00,2019
11377,100100826.00,TỔNG CÔNG TY CỔ PHẦN DỆT MAY HÀ NỘI,3.00,13110.00,1.00,1187523.00,11586.10,2407.00,2471.00,2019

B3

In [ ]:
invalid_labor = df_2019[df_2019['SoLaodong_CuoiNam'] < 0]
print(f"Lao động < 0: {len(invalid_labor)} dòng")

revenue_q1 = df_2019['TongDoanhthu_DTDN'].quantile(0.01)
revenue_q99 = df_2019['TongDoanhthu_DTDN'].quantile(0.99)
print(f"Doanh thu 1% thấp nhất: {revenue_q1}")
print(f"Doanh thu 99% cao nhất: {revenue_q99}")

top_10_revenue = df_2019.nlargest(10, 'TongDoanhthu_DTDN')
print("\n--- Top 10 Doanh thu ---")
display(top_10_revenue[['Masothue', 'TenDN', 'TongDoanhthu_DTDN']])

df_2019['Abs_Loinhuan'] = df_2019['Loinhuan_SauThue'].abs()
top_10_abs_profit = df_2019.nlargest(10, 'Abs_Loinhuan')
print("\n--- Top 10 Trị tuyệt đối Lợi nhuận ---")
display(top_10_abs_profit[['Masothue', 'TenDN', 'Loinhuan_SauThue', 'Abs_Loinhuan']])

Lao động < 0: 0 dòng
Doanh thu 1% thấp nhất: 0.0
Doanh thu 99% cao nhất: 2137007.0339999986

--- Top 10 Doanh thu ---

,Masothue,TenDN,TongDoanhthu_DTDN
27654,4601124536,CÔNG TY TRÁCH NHIỆM HỮU HẠN SAMSUNG ELECTRONIC...,655008211.00
35099,2300325764,CÔNG TY TRÁCH NHIỆM HỮU HẠN SAMSUNG ELECTRONIC...,445230680.00
35682,2300852009,CÔNG TY TRÁCH NHIỆM HỮU HẠN SAMSUNG DISPLAY VI...,329411426.80
84807,300942001,TỔNG CTY TNHH ĐIỆN LỰC MIỀN NAM TNHH,128946577.00
8670,100107370,TẬP ĐOÀN XĂNG DẦU VIỆT NAM,127815852.00
1918,100100417,TỔNG C.TY ĐIỆN LỰC MIỀN BẮC,120611977.00
32643,2500150543,CÔNG TY HONDA VIỆT NAM,109266447.70
8908,5700100256,TẬP ĐOÀN CÔNG NGHIỆP THAN – KHOÁNG SẢN VIỆT NAM,103052858.00
61216,4300378569,CÔNG TY CỔ PHẦN LỌC HÓA DẦU BÌNH SƠN,102724546.00
89634,313055543,CTY TNHH ĐIỆN TỬ SAMSUNG HCMC CE COMPLEX,98377123.00

--- Top 10 Trị tuyệt đối Lợi nhuận ---

,Masothue,TenDN,Loinhuan_SauThue,Abs_Loinhuan
90270,313862434,CTY TNHH CÔNG NGHỆ TÂN HOÀN CẦU,-889460688.40,889460688.40
5870,107842658,CÔNG TY TRÁCH NHIỆM HỮU HẠN MTL VIỆT NAM,-182354403.10,182354403.10
27654,4601124536,CÔNG TY TRÁCH NHIỆM HỮU HẠN SAMSUNG ELECTRONIC...,46082609.80,46082609.80
35099,2300325764,CÔNG TY TRÁCH NHIỆM HỮU HẠN SAMSUNG ELECTRONIC...,35028943.70,35028943.70
49575,2801149686,CÔNG TY TRÁCH NHIỆM HỮU HẠN LỌC HÓA DẦU NGHI SƠN,-22683859.80,22683859.80
32643,2500150543,CÔNG TY HONDA VIỆT NAM,20257749.20,20257749.20
131513,106205215,Công Ty TNHH ĐầU Tư Và PHáT TRIểN Đô THị GIA LâM,13092888.90,13092888.90
82615,3500102710,TỔNG CÔNG TY KHÍ VIỆT NAM - CÔNG TY CỔ PHẦN,11920871.50,11920871.50
648425,3500102710,TổNG CôNG TY KHí VIệT NAM - CôNG TY Cổ PHầN,11920871.50,11920871.50
35682,2300852009,CÔNG TY TRÁCH NHIỆM HỮU HẠN SAMSUNG DISPLAY VI...,11653003.40,11653003.40

'\nGiải thích (bạn viết thêm):\n- Bạn không nên xóa 1% dữ liệu lớn nhất một cách mù quáng vì trong kinh tế học, 1% doanh nghiệp lớn nhất (Tập đoàn lớn, Vingroup, Viettel...) thường chiếm phần lớn doanh thu của nền kinh tế. Xóa đi sẽ làm sai lệch dữ liệu.\n- Bạn sẽ loại bỏ (drop) các quan sát khi: Lao động < 0 (lỗi nhập liệu), doanh thu bị âm vô lý.\n- Dữ liệu bị skewed (lệch): Yêu cầu bài toán đã nhắc nhở luôn dùng cả `mean` và `median` khi phân tích doanh thu và lợi nhuận vì số liệu bị lệch sang phải (do một vài cty siêu lớn kéo mean lên cao).\n'

VSIC

In [ ]:
df_2019['MaNganhSXKD_Chinh'] = df_2019['MaNganhSXKD_Chinh'].astype(str).str.replace(r'\.0$', '', regex=True)
df_2019['MaNganhSXKD_Chinh'] = df_2019['MaNganhSXKD_Chinh'].str.zfill(4) # Điền 0 vào đầu nếu đủ 4 số

df_2019['VSIC_2_digit'] = df_2019['MaNganhSXKD_Chinh'].str[:2]

EXTRA

In [24]:
df_2019.sample(10)

,Masothue,TenDN,LoaihinhKT,MaNganhSXKD_Chinh,MaTinh_Dieutra,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ,Year,Abs_Loinhuan,VSIC_2_digit
117113,1900445042,CÔNG TY TNHH THƯƠNG MẠI - DỊCH VỤ MÔI TRƯỜNG T...,8.00,71200,95.00,1440.00,0.00,12.00,10.00,2019,0.00,71
388184,6001615977,Công Ty Cổ Phần Area Group,9.00,85600,66.00,NaN,0.00,1.00,1.00,2019,0.00,85
556200,315250194,CÔNG TY TRÁCH NHIỆM HỮU HẠN ĐẦU TƯ THƯƠNG MẠI ...,8.00,46497,79.00,NaN,-14.00,3.00,3.00,2019,14.00,46
392091,5801004968,CÔNG TY TNHH VƯỜN CẢNH BÍCH CÂU,8.00,56101,68.00,NaN,204.10,9.00,22.00,2019,204.10,56
254981,5701656543,Công Ty TNHH 1 Thành Viên Quyền Ngọc Phượng Lâm,8.00,3110,22.00,NaN,0.00,5.00,5.00,2019,0.00,31
662339,2100651400,Cty TNHH THƯƠNG MẠI DỊCH VỤ XÂY DỰNG HỶ HỶ,8.00,56302,84.00,NaN,3.40,5.00,5.00,2019,3.40,56
110825,1501090976,CÔNG TY TRÁCH NHIỆM HỮU HẠN MTV THƯƠNG MẠI DỊC...,8.00,55101,86.00,204.00,-87.70,4.00,4.00,2019,87.70,55
24057,5600304545,CÔNG TY TRÁCH NHIỆM HỮU HẠN CÔNG NGHỆ UMAX,8.00,47411,11.00,885.20,30.10,5.00,5.00,2019,30.10,47
667238,1601978028,Cty TNHH Thiết Bị Và Công Nghệ Uy Vũ,8.00,46592,89.00,NaN,38.30,9.00,9.00,2019,38.30,46
58203,401597030,CÔNG TY TRÁCH NHIỆM HỮU HẠN BỆNH VIỆN ĐA KHOA ...,8.00,86101,48.00,7764.30,-1760.50,47.00,38.00,2019,1760.50,86

In [29]:
df_2019_raw['DN_MaTinh'].value_counts()

DN_MaTinh
79.00    228740
1.00     141978
74.00     24140
75.00     19461
48.00     16799
          ...
2.00       1054
11.00       993
4.00        989
12.00       900
6.00        630
Name: count, Length: 63, dtype: int64

In [31]:
df_2019_raw.isna().sum()

NamSL                  1
LoaiPhieu_Dieutra      1
MaTinh_Dieutra         1
MaHuyen_Dieutra        1
MaXa_Dieutra         211
                    ...
PhaiTra_NguoiLD        2
VayNoTC_NH             2
DP_Phaitra_NH          2
VonGop_ChuSH           2
LoinhuanST_ChuaPP      2
Length: 156, dtype: int64

In [ ]:
# Lọc các cột liên quan đến doanh thu, lợi nhuận và số lao động
columns_to_keep = [
    'Masothue', 'TenDN', 'DN_MaTinh', 'MaNganhSXKD_Chinh', # Thông tin chung
    'TongDoanhthu_DTDN', 'Doanhthu_Thuan_BH_CCDV', # Doanh thu
    'Loinhuan_TruocThue', 'Loinhuan_SauThue', # Lợi nhuận
    'SoLaodong_DauNam', 'SoLaodong_CuoiNam', 'SoLaodong_BQ' # Số lao động
]

# Tạo dataframe mới chỉ chứa các cột cần thiết
df_focus = df_2019_raw[columns_to_keep].copy()

# Xem thử dữ liệu
df_focus.head()

In [32]:
df_2019_raw[df_2019_raw.isna().all(axis=1)]

,NamSL,LoaiPhieu_Dieutra,MaTinh_Dieutra,MaHuyen_Dieutra,MaXa_Dieutra,DN_MaTinh,DN_MaHuyen,DN_MaXa,Masothue,Masothue2,TenDN,Diachi,Dienthoai,Fax,Email,LoaihinhKT,LoaihinhKT2,Tyle_Von_NNTW,Tyle_Von_NNDP,Tyle_Von_NN,Nhanuoc_CoChiphoi,Tyle_Von_Nuocngoai,CoMua_HHDV_Nuocngoai,Tongtien_Tra_Nuocngoai,CoBan_HHDV_Nuocngoai,Tongtien_Thu_Nuocngoai,SoLaodong_DauNam,SoLaodong_DauNam_Nu,SoLaodong_CuoiNam,SoLaodong_Cuoinam_Nganh,SoLaodong_CuoiNam_Nu,SoLaodong_BQ,SoLaodong_BHXH,SoLaodong_KhongLuong,SoLaodong_Nuocngoai,Tongtien_Tra_NguoiLD,Tongtien_BHXH_Tra,Tongtien_Donggop,TonDauNam,TonDauNam_CN,TonDauNam_CN_Dodang,TonDauNam_CN_Thanhpham,TonDauNam_CN_GuiBan,TonCuoiNam,TonCuoiNam_CN,TonCuoiNam_CN_Dodang,TonCuoiNam_CN_Thanhpham,TonCuoiNam_CN_GuiBan,TongDoanhthu_DTDN,MaNganhSXKD_Chinh,Doanhthu_Nganh,Co_Vondautu,Co_GiacongLaprap,VonDieuLe_Tongso,GopVonDieuLe_Tongso,GopVonDieuLeLuyke_Tongso,VonDieuLe_VietNam,GopVonDieuLe_VietNam,GopVonDieuLeLuyke_VietNam,VonDieuLe_NhaNuoc,GopVonDieuLe_NhaNuoc,GopVonDieuLeLuyke_NhaNuoc,VonDieuLe_NgoaiNhaNuoc,GopVonDieuLe_NgoaiNhaNuoc,GopVonDieuLeLuyke_NgoaiNhaNuoc,VonDieuLe_Khac,GopVonDieuLe_Khac,GopVonDieuLeLuyke_Khac,VonDieuLe_NuocNgoai,GopVonDieuLe_NuocNgoai,GopVonDieuLeLuyke_NuocNgoai,TinhtrangHD,TongVondautu,Co_BCTC,DKThue_TTHD,DKThue_NamBD,LaDoituongChonMau1A,MaNganhC4,Khuvuc,NhomLaodong,Taisan_Tong_DK,Taisan_Tong_CK,Taisan_NH_DK,Taisan_NH_CK,Tonkho_DK,Tonkho_CK,Taisan_DH_DK,Taisan_DH_CK,TSCD_Nguyengia_DK,TSCD_Nguyengia_CK,TSCD_HMLK_DK,TSCD_HMLK_CK,TSCD_Huuhinh_DK,TSCD_Huuhinh_CK,TSCD_ThueTC_DK,TSCD_ThueTC_CK,TSCD_Vohinh_DK,TSCD_Vohinh_CK,TSCD_Huuhinh_Nguyengia_DK,TSCD_Huuhinh_Nguyengia_CK,TSCD_ThueTC_Nguyengia_DK,TSCD_ThueTC_Nguyengia_CK,TSCD_Vohinh_Nguyengia_DK,TSCD_Vohinh_Nguyengia_CK,TSCD_Huuhinh_HMLK_DK,TSCD_Huuhinh_HMLK_CK,TSCD_ThueTC_HMLK_DK,TSCD_ThueTC_HMLK_CK,TSCD_Vohinh_HMLK_DK,TSCD_Vohinh_HMLK_CK,Chiphi_XDCB_Dodang_DK,Chiphi_XDCB_Dodang_CK,Nguonvon_Tong_DK,Nguonvon_Tong_CK,Von_ChuSohuu_DK,Von_ChuSohuu_CK,Doanhthu_BH_CCDV,Giamtru_Doanhthu,Doanhthu_Thuan_BH_CCDV,Gia_VonHangban,Doanhthu_HDTC,Thunhap_Khac,Loinhuan_TruocThue,Chiphi_Thue_TNDN,TSCD_DK,TSCD_CK,NoPhaitra_DK,NoPhaitra_CK,ChiThueHL,LoinhuanGop,Chi_TC,Chi_TC_LV,Chi_BHang,Chi_QLDN,Loinhuan_Thuan,Chi_Khac,Loinhuan_Khac,Loinhuan_SauThue,Lai_CPhieu,Tien,DautuTC_NH,PhaiThu_NH,PhaiThu_NH_KH,Tratruoc_NBan_NH,BDS_Dautu,BDS_Dautu_NGia,BDS_Dautu_HMLK,Taisan_DH_Khac,Phaitra_NBan_NH,NMua_Tratruoc_NH,Thue,PhaiTra_NguoiLD,VayNoTC_NH,DP_Phaitra_NH,VonGop_ChuSH,LoinhuanST_ChuaPP
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df_2019_raw['MaTinh_Dieutra'] = df_2019_raw['MaTinh_Dieutra'].astype('Int64').astype(str)
df_2019_raw['LoaihinhKT'] = df_2019_raw['LoaihinhKT'].astype('Int64').astype(str)
df_2019_raw['Masothue'] = df_2019_raw['Masothue'].astype('Int64').astype(str)
df_2019_raw = df_2019_raw.dropna(how='all')

In [35]:
# Lọc các doanh nghiệp có Tổng doanh thu = 0 và Lợi nhuận sau thuế < 0
condition = (df_2019['TongDoanhthu_DTDN'] == 0) & (df_2019['Loinhuan_SauThue'] < 0)
dn_thoa_man = df_2019[condition]

print(f"Số lượng doanh nghiệp có doanh thu = 0 và LNST < 0: {len(dn_thoa_man)}")
display(dn_thoa_man.head())

Số lượng doanh nghiệp có doanh thu = 0 và LNST < 0: 791

,Masothue,TenDN,LoaihinhKT,MaNganhSXKD_Chinh,MaTinh_Dieutra,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ,Year,Abs_Loinhuan,VSIC_2_digit
87,100113448,CHI NHÁNH DS AVOCATS TẠI HÀ NỘI,11.00,69102,1.00,0.00,-138.60,2.00,2.00,2019,138.60,69
149,106175320,CÔNG TY TRÁCH NHIỆM HỮU HẠN CAREGO (VIỆT NAM),11.00,62010,1.00,0.00,-29.20,3.00,0.00,2019,29.20,62
236,102743300,CÔNG TY CỔ PHẦN VINAFACADE,12.00,43300,1.00,0.00,-516.90,3.00,3.00,2019,516.90,43
249,104264409,CÔNG TY CỔ PHẦN VIGLACERA DETA,9.00,43290,1.00,0.00,-311.90,1.00,1.00,2019,311.90,43
319,305400669,CÔNG TY TRÁCH NHIỆM HỮU HẠN CÔNG TRÌNH ĐỊA CHẤ...,11.00,42990,1.00,0.00,-470.50,1.00,1.00,2019,470.50,42

In [38]:
# Tính quantile 99 cho Doanh thu ngành, Lợi nhuận sau thuế, và Lao động cuối năm
cols_to_check = ['Doanhthu_Nganh', 'Loinhuan_SauThue', 'SoLaodong_CuoiNam']
quantile_99 = df_2019_raw[cols_to_check].quantile(0.99)

print("Giá trị phân vị 99 (Quantile 99):")
print(quantile_99)

Giá trị phân vị 99 (Quantile 99):
Doanhthu_Nganh      427476.92
Loinhuan_SauThue      9998.22
SoLaodong_CuoiNam      270.00
Name: 0.99, dtype: float64