In [1]:
import pandas as pd
import numpy as np

In [4]:
df_2019=pd.read_excel('/Users/duc/Code/data-prepare-and-visualize/Bieu 1A.00&Suy rong B_DN 2019.xlsx')

In [ ]:
df_2018=pd.read_excel(r"E:\OneDrive - National Economics University\tailieugiangday2\VIZ_DSEB\Project_VES\Bieu 1A.00_DN 2018.xlsx")

In [ ]:
df_2018.shape

(622393, 133)

In [ ]:
df_2019.shape

(689251, 156)

In [ ]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689251 entries, 0 to 689250
Columns: 156 entries, NamSL to LoinhuanST_ChuaPP
dtypes: float64(149), object(7)
memory usage: 820.3+ MB

In [ ]:
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 622393 entries, 0 to 622392
Columns: 133 entries, Mã tỉnh to Unnamed: 132
dtypes: float64(28), object(105)
memory usage: 631.5+ MB

In [ ]:
df_2019.head()

,NamSL,LoaiPhieu_Dieutra,MaTinh_Dieutra,MaHuyen_Dieutra,MaXa_Dieutra,DN_MaTinh,DN_MaHuyen,DN_MaXa,Masothue,Masothue2,...,BDS_Dautu_HMLK,Taisan_DH_Khac,Phaitra_NBan_NH,NMua_Tratruoc_NH,Thue,PhaiTra_NguoiLD,VayNoTC_NH,DP_Phaitra_NH,VonGop_ChuSH,LoinhuanST_ChuaPP
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020.0,A,1.0,1.0,1.0,1.0,1.0,1.0,100512361.0,NaN,...,0.0,0.0,3303.8,101.1,19.6,0.0,38604.5,0.0,0.0,1810.8
2,2020.0,A,1.0,1.0,1.0,1.0,1.0,1.0,100998568.0,NaN,...,0.0,226.7,5355.0,22.7,715.9,0.0,18540.9,0.0,15680.0,-9781.0
3,2020.0,A,1.0,1.0,1.0,1.0,1.0,1.0,101063863.0,NaN,...,0.0,992.7,22.2,405.4,0.0,0.0,0.0,0.0,600.0,116.2
4,2020.0,A,1.0,1.0,1.0,1.0,1.0,1.0,101070772.0,NaN,...,0.0,5.0,1666.2,0.0,3.5,0.0,121.8,0.0,1994.1,-2863.8

In [ ]:
df_2019.columns.tolist()

['NamSL',
 'LoaiPhieu_Dieutra',
 'MaTinh_Dieutra',
 'MaHuyen_Dieutra',
 'MaXa_Dieutra',
 'DN_MaTinh',
 'DN_MaHuyen',
 'DN_MaXa',
 'Masothue',
 'Masothue2',
 'TenDN',
 'Diachi',
 'Dienthoai',
 'Fax',
 'Email',
 'LoaihinhKT',
 'LoaihinhKT2',
 'Tyle_Von_NNTW',
 'Tyle_Von_NNDP',
 'Tyle_Von_NN',
 'Nhanuoc_CoChiphoi',
 'Tyle_Von_Nuocngoai',
 'CoMua_HHDV_Nuocngoai',
 'Tongtien_Tra_Nuocngoai',
 'CoBan_HHDV_Nuocngoai',
 'Tongtien_Thu_Nuocngoai',
 'SoLaodong_DauNam',
 'SoLaodong_DauNam_Nu',
 'SoLaodong_CuoiNam',
 'SoLaodong_Cuoinam_Nganh',
 'SoLaodong_CuoiNam_Nu',
 'SoLaodong_BQ',
 'SoLaodong_BHXH',
 'SoLaodong_KhongLuong',
 'SoLaodong_Nuocngoai',
 'Tongtien_Tra_NguoiLD',
 'Tongtien_BHXH_Tra',
 'Tongtien_Donggop',
 'TonDauNam',
 'TonDauNam_CN',
 'TonDauNam_CN_Dodang',
 'TonDauNam_CN_Thanhpham',
 'TonDauNam_CN_GuiBan',
 'TonCuoiNam',
 'TonCuoiNam_CN',
 'TonCuoiNam_CN_Dodang',
 'TonCuoiNam_CN_Thanhpham',
 'TonCuoiNam_CN_GuiBan',
 'TongDoanhthu_DTDN',
 'MaNganhSXKD_Chinh',
 'Doanhthu_Nganh',
 'Co_Vondautu',
 'Co_GiacongLaprap',
 'VonDieuLe_Tongso',
 'GopVonDieuLe_Tongso',
 'GopVonDieuLeLuyke_Tongso',
 'VonDieuLe_VietNam',
 'GopVonDieuLe_VietNam',
 'GopVonDieuLeLuyke_VietNam',
 'VonDieuLe_NhaNuoc',
 'GopVonDieuLe_NhaNuoc',
 'GopVonDieuLeLuyke_NhaNuoc',
 'VonDieuLe_NgoaiNhaNuoc',
 'GopVonDieuLe_NgoaiNhaNuoc',
 'GopVonDieuLeLuyke_NgoaiNhaNuoc',
 'VonDieuLe_Khac',
 'GopVonDieuLe_Khac',
 'GopVonDieuLeLuyke_Khac',
 'VonDieuLe_NuocNgoai',
 'GopVonDieuLe_NuocNgoai',
 'GopVonDieuLeLuyke_NuocNgoai',
 'TinhtrangHD',
 'TongVondautu',
 'Co_BCTC',
 'DKThue_TTHD',
 'DKThue_NamBD',
 'LaDoituongChonMau1A',
 'MaNganhC4',
 'Khuvuc',
 'NhomLaodong',
 'Taisan_Tong_DK',
 'Taisan_Tong_CK',
 'Taisan_NH_DK',
 'Taisan_NH_CK',
 'Tonkho_DK',
 'Tonkho_CK',
 'Taisan_DH_DK',
 'Taisan_DH_CK',
 'TSCD_Nguyengia_DK',
 'TSCD_Nguyengia_CK',
 'TSCD_HMLK_DK',
 'TSCD_HMLK_CK',
 'TSCD_Huuhinh_DK',
 'TSCD_Huuhinh_CK',
 'TSCD_ThueTC_DK',
 'TSCD_ThueTC_CK',
 'TSCD_Vohinh_DK',
 'TSCD_Vohinh_CK',
 'TSCD_Huuhinh_Nguyengia_DK',
 'TSCD_Huuhinh_Nguyengia_CK',
 'TSCD_ThueTC_Nguyengia_DK',
 'TSCD_ThueTC_Nguyengia_CK',
 'TSCD_Vohinh_Nguyengia_DK',
 'TSCD_Vohinh_Nguyengia_CK',
 'TSCD_Huuhinh_HMLK_DK',
 'TSCD_Huuhinh_HMLK_CK',
 'TSCD_ThueTC_HMLK_DK',
 'TSCD_ThueTC_HMLK_CK',
 'TSCD_Vohinh_HMLK_DK',
 'TSCD_Vohinh_HMLK_CK',
 'Chiphi_XDCB_Dodang_DK',
 'Chiphi_XDCB_Dodang_CK',
 'Nguonvon_Tong_DK',
 'Nguonvon_Tong_CK',
 'Von_ChuSohuu_DK',
 'Von_ChuSohuu_CK',
 'Doanhthu_BH_CCDV',
 'Giamtru_Doanhthu',
 'Doanhthu_Thuan_BH_CCDV',
 'Gia_VonHangban',
 'Doanhthu_HDTC',
 'Thunhap_Khac',
 'Loinhuan_TruocThue',
 'Chiphi_Thue_TNDN',
 'TSCD_DK',
 'TSCD_CK',
 'NoPhaitra_DK',
 'NoPhaitra_CK',
 'ChiThueHL',
 'LoinhuanGop',
 'Chi_TC',
 'Chi_TC_LV',
 'Chi_BHang',
 'Chi_QLDN',
 'Loinhuan_Thuan',
 'Chi_Khac',
 'Loinhuan_Khac',
 'Loinhuan_SauThue',
 'Lai_CPhieu',
 'Tien',
 'DautuTC_NH',
 'PhaiThu_NH',
 'PhaiThu_NH_KH',
 'Tratruoc_NBan_NH',
 'BDS_Dautu',
 'BDS_Dautu_NGia',
 'BDS_Dautu_HMLK',
 'Taisan_DH_Khac',
 'Phaitra_NBan_NH',
 'NMua_Tratruoc_NH',
 'Thue',
 'PhaiTra_NguoiLD',
 'VayNoTC_NH',
 'DP_Phaitra_NH',
 'VonGop_ChuSH',
 'LoinhuanST_ChuaPP']

In [ ]:
for col in df_2019.columns:
    print(col)

NamSL
LoaiPhieu_Dieutra
MaTinh_Dieutra
MaHuyen_Dieutra
MaXa_Dieutra
DN_MaTinh
DN_MaHuyen
DN_MaXa
Masothue
Masothue2
TenDN
Diachi
Dienthoai
Fax
Email
LoaihinhKT
LoaihinhKT2
Tyle_Von_NNTW
Tyle_Von_NNDP
Tyle_Von_NN
Nhanuoc_CoChiphoi
Tyle_Von_Nuocngoai
CoMua_HHDV_Nuocngoai
Tongtien_Tra_Nuocngoai
CoBan_HHDV_Nuocngoai
Tongtien_Thu_Nuocngoai
SoLaodong_DauNam
SoLaodong_DauNam_Nu
SoLaodong_CuoiNam
SoLaodong_Cuoinam_Nganh
SoLaodong_CuoiNam_Nu
SoLaodong_BQ
SoLaodong_BHXH
SoLaodong_KhongLuong
SoLaodong_Nuocngoai
Tongtien_Tra_NguoiLD
Tongtien_BHXH_Tra
Tongtien_Donggop
TonDauNam
TonDauNam_CN
TonDauNam_CN_Dodang
TonDauNam_CN_Thanhpham
TonDauNam_CN_GuiBan
TonCuoiNam
TonCuoiNam_CN
TonCuoiNam_CN_Dodang
TonCuoiNam_CN_Thanhpham
TonCuoiNam_CN_GuiBan
TongDoanhthu_DTDN
MaNganhSXKD_Chinh
Doanhthu_Nganh
Co_Vondautu
Co_GiacongLaprap
VonDieuLe_Tongso
GopVonDieuLe_Tongso
GopVonDieuLeLuyke_Tongso
VonDieuLe_VietNam
GopVonDieuLe_VietNam
GopVonDieuLeLuyke_VietNam
VonDieuLe_NhaNuoc
GopVonDieuLe_NhaNuoc
GopVonDieuLeLuyke_NhaNuoc
VonDieuLe_NgoaiNhaNuoc
GopVonDieuLe_NgoaiNhaNuoc
GopVonDieuLeLuyke_NgoaiNhaNuoc
VonDieuLe_Khac
GopVonDieuLe_Khac
GopVonDieuLeLuyke_Khac
VonDieuLe_NuocNgoai
GopVonDieuLe_NuocNgoai
GopVonDieuLeLuyke_NuocNgoai
TinhtrangHD
TongVondautu
Co_BCTC
DKThue_TTHD
DKThue_NamBD
LaDoituongChonMau1A
MaNganhC4
Khuvuc
NhomLaodong
Taisan_Tong_DK
Taisan_Tong_CK
Taisan_NH_DK
Taisan_NH_CK
Tonkho_DK
Tonkho_CK
Taisan_DH_DK
Taisan_DH_CK
TSCD_Nguyengia_DK
TSCD_Nguyengia_CK
TSCD_HMLK_DK
TSCD_HMLK_CK
TSCD_Huuhinh_DK
TSCD_Huuhinh_CK
TSCD_ThueTC_DK
TSCD_ThueTC_CK
TSCD_Vohinh_DK
TSCD_Vohinh_CK
TSCD_Huuhinh_Nguyengia_DK
TSCD_Huuhinh_Nguyengia_CK
TSCD_ThueTC_Nguyengia_DK
TSCD_ThueTC_Nguyengia_CK
TSCD_Vohinh_Nguyengia_DK
TSCD_Vohinh_Nguyengia_CK
TSCD_Huuhinh_HMLK_DK
TSCD_Huuhinh_HMLK_CK
TSCD_ThueTC_HMLK_DK
TSCD_ThueTC_HMLK_CK
TSCD_Vohinh_HMLK_DK
TSCD_Vohinh_HMLK_CK
Chiphi_XDCB_Dodang_DK
Chiphi_XDCB_Dodang_CK
Nguonvon_Tong_DK
Nguonvon_Tong_CK
Von_ChuSohuu_DK
Von_ChuSohuu_CK
Doanhthu_BH_CCDV
Giamtru_Doanhthu
Doanhthu_Thuan_BH_CCDV
Gia_VonHangban
Doanhthu_HDTC
Thunhap_Khac
Loinhuan_TruocThue
Chiphi_Thue_TNDN
TSCD_DK
TSCD_CK
NoPhaitra_DK
NoPhaitra_CK
ChiThueHL
LoinhuanGop
Chi_TC
Chi_TC_LV
Chi_BHang
Chi_QLDN
Loinhuan_Thuan
Chi_Khac
Loinhuan_Khac
Loinhuan_SauThue
Lai_CPhieu
Tien
DautuTC_NH
PhaiThu_NH
PhaiThu_NH_KH
Tratruoc_NBan_NH
BDS_Dautu
BDS_Dautu_NGia
BDS_Dautu_HMLK
Taisan_DH_Khac
Phaitra_NBan_NH
NMua_Tratruoc_NH
Thue
PhaiTra_NguoiLD
VayNoTC_NH
DP_Phaitra_NH
VonGop_ChuSH
LoinhuanST_ChuaPP

In [ ]:
important_cols_2019 = [
    'Masothue',
    'TenDN',
    'LoaihinhKT',
    'MaTinh_Dieutra',
    'Doanhthu_Nganh',
    'MaNganhSXKD_Chinh',
    'Doanhthu_BH_CCDV',
    'TongDoanhthu_DTDN',
    'Loinhuan_SauThue',
    'SoLaodong_CuoiNam',
    'SoLaodong_BQ'
]

In [ ]:
df_2019_core=df_2019[important_cols_2019]

In [ ]:
df_2019_core.columns.tolist()

['Masothue',
 'TenDN',
 'LoaihinhKT',
 'MaTinh_Dieutra',
 'Doanhthu_Nganh',
 'MaNganhSXKD_Chinh',
 'Doanhthu_BH_CCDV',
 'TongDoanhthu_DTDN',
 'Loinhuan_SauThue',
 'SoLaodong_CuoiNam',
 'SoLaodong_BQ']

In [ ]:
df_2019_core.head()

,Masothue,TenDN,LoaihinhKT,MaTinh_Dieutra,Doanhthu_Nganh,MaNganhSXKD_Chinh,Doanhthu_BH_CCDV,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100512361.0,CÔNG TY TRÁCH NHIỆM HỮU HẠN THƯƠNG MẠI VÀ BAO ...,8.0,1.0,59577.0,22201.0,NaN,59577.0,150.2,30.0,31.0
2,100998568.0,CÔNG TY TRÁCH NHIỆM HỮU HẠN TÂN HÀ SÁNG,8.0,1.0,8737.0,14100.0,NaN,58413.0,-3766.3,66.0,65.0
3,101063863.0,CÔNG TY TRÁCH NHIỆM HỮU HẠN HAI CHI,8.0,1.0,1873.0,13920.0,NaN,1873.0,4.4,7.0,7.0
4,101070772.0,DOANH NGHIỆP TƯ NHÂN NHÂN SẢN XUẤT VÀ THƯƠNG M...,6.0,1.0,1149.0,16292.0,NaN,1436.0,12.4,5.0,5.0

In [ ]:
df_2019_core.describe()

,Masothue,LoaihinhKT,MaTinh_Dieutra,Doanhthu_Nganh,MaNganhSXKD_Chinh,Doanhthu_BH_CCDV,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ
count,6.892500e+05,689250.000000,689250.000000,6.892500e+05,689250.000000,0.0,1.178670e+05,6.892490e+05,689250.000000,6.883820e+05
mean,1.439717e+09,8.078627,51.108229,3.404644e+04,46925.618130,NaN,1.518712e+05,-7.516129e+02,21.246253,1.024323e+02
std,1.732218e+09,1.002255,32.197130,1.159932e+06,18711.676349,NaN,2.897129e+06,1.097796e+06,265.712561,2.177646e+04
min,1.013000e+03,1.000000,1.000000,-2.406915e+05,1110.000000,NaN,0.000000e+00,-8.894607e+08,1.000000,0.000000e+00
25%,3.034694e+08,8.000000,24.000000,6.400000e+01,41020.000000,NaN,1.073000e+03,-3.530000e+01,2.000000,2.000000e+00
50%,3.149527e+08,8.000000,68.000000,1.303300e+03,46599.000000,NaN,6.674400e+03,0.000000e+00,4.000000,4.000000e+00
75%,2.801994e+09,8.000000,79.000000,7.416975e+03,52299.000000,NaN,3.749850e+04,2.130000e+01,9.000000,9.000000e+00
max,8.237862e+09,13.000000,96.000000,6.539492e+08,99000.000000,NaN,6.550082e+08,4.608261e+07,63958.000000,9.000000e+06

In [ ]:
df_2019_core.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689251 entries, 0 to 689250
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Masothue           689250 non-null  float64
 1   TenDN              689250 non-null  object
 2   LoaihinhKT         689250 non-null  float64
 3   MaTinh_Dieutra     689250 non-null  float64
 4   Doanhthu_Nganh     689250 non-null  float64
 5   MaNganhSXKD_Chinh  689250 non-null  float64
 6   Doanhthu_BH_CCDV   0 non-null       float64
 7   TongDoanhthu_DTDN  117867 non-null  float64
 8   Loinhuan_SauThue   689249 non-null  float64
 9   SoLaodong_CuoiNam  689250 non-null  float64
 10  SoLaodong_BQ       688382 non-null  float64
dtypes: float64(10), object(1)
memory usage: 57.8+ MB

In [ ]:
df_2019_core.sample(10)

,Masothue,TenDN,LoaihinhKT,MaTinh_Dieutra,Doanhthu_Nganh,MaNganhSXKD_Chinh,Doanhthu_BH_CCDV,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ
511608,3.046964e+08,Cty CP TV XD ĐT Việt,9.0,79.0,798.6,43900.0,NaN,NaN,-161.6,2.0,5.0
95423,3.045253e+08,CTY TNHH HẢI KHANG,8.0,79.0,92.0,18110.0,NaN,92.0,2.2,1.0,1.0
139923,1.073187e+08,CÔNG TY TNHH ĐẦU TƯ VÀ KINH DOANH THƯƠNG MẠI T...,8.0,1.0,0.0,52109.0,NaN,NaN,-3.8,1.0,1.0
282139,2.013024e+08,CT TNHH Dịch Thuật Và Đào Tạo Linh Anh,8.0,31.0,0.0,82199.0,NaN,NaN,-2.0,1.0,1.0
228311,1.082632e+08,CôNG TY TNHH CôNG NGHệ MáY DANH SơN,8.0,1.0,1192.2,46599.0,NaN,NaN,-124.4,3.0,3.0
542331,3.151330e+08,CÔNG TY TNHH VIETSKY TRAVEL,8.0,79.0,1408.5,82300.0,NaN,NaN,2.8,1.0,1.0
14713,1.061198e+08,CÔNG TY TRÁCH NHIỆM HỮU HẠN DỊCH VỤ VÀ THƯƠNG ...,8.0,1.0,3568.0,43210.0,NaN,3568.0,47.3,10.0,10.0
422915,3.603224e+09,Công Ty Trách Nhiệm Hữu Hạn Gỗ Khang Vy,8.0,75.0,66732.4,46631.0,NaN,NaN,213.7,2.0,2.0
96275,3.054860e+08,CTY TNHH GIẢI PHÁP SỐ TOÀN CẦU,13.0,79.0,32940.2,46510.0,NaN,32940.2,4625.2,13.0,14.0
615301,3.107653e+08,Công Ty TNHH Một Thành Viên Thương Mại Dịch Vụ...,8.0,79.0,0.0,64920.0,NaN,NaN,-2.0,1.0,1.0

In [ ]:
df_2019_core.isna().sum()

Masothue                  1
TenDN                     1
LoaihinhKT                1
MaTinh_Dieutra            1
Doanhthu_Nganh            1
MaNganhSXKD_Chinh         1
Doanhthu_BH_CCDV     689251
TongDoanhthu_DTDN    571384
Loinhuan_SauThue          2
SoLaodong_CuoiNam         1
SoLaodong_BQ            869
dtype: int64

In [ ]:
missing = pd.DataFrame({
    'Missing': df_2019_core.isna().sum(),
    'Percent': df_2019_core.isna().mean() * 100
})

missing

                   Missing     Percent
Masothue                 1    0.000145
TenDN                    1    0.000145
LoaihinhKT               1    0.000145
MaTinh_Dieutra           1    0.000145
Doanhthu_Nganh           1    0.000145
MaNganhSXKD_Chinh        1    0.000145
Doanhthu_BH_CCDV    689251  100.000000
TongDoanhthu_DTDN   571384   82.899263
Loinhuan_SauThue         2    0.000290
SoLaodong_CuoiNam        1    0.000145
SoLaodong_BQ           869    0.126079

In [ ]:
df_2019_core.isna().all(axis=1).sum()

np.int64(1)

In [ ]:
df_2019_core[df_2019_core.isna().all(axis=1)]

,Masothue,TenDN,LoaihinhKT,MaTinh_Dieutra,Doanhthu_Nganh,MaNganhSXKD_Chinh,Doanhthu_BH_CCDV,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_2019_core=df_2019_core.dropna(how='all')

In [ ]:
df_2019_dralf=df_2019_core.dropna(subset=['Loinhuan_SauThue'])

In [ ]:
df_2019_dralf.shape

(689249, 11)

In [ ]:
df_2019_core.loc[0:4, 'LoaihinhKT']

1    8.0
2    8.0
3    8.0
4    6.0
Name: LoaihinhKT, dtype: float64

In [ ]:
df_2019_core.loc[0:4]

,Masothue,TenDN,LoaihinhKT,MaTinh_Dieutra,Doanhthu_Nganh,MaNganhSXKD_Chinh,Doanhthu_BH_CCDV,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ
1,100512361.0,CÔNG TY TRÁCH NHIỆM HỮU HẠN THƯƠNG MẠI VÀ BAO ...,8.0,1.0,59577.0,22201.0,NaN,59577.0,150.2,30.0,31.0
2,100998568.0,CÔNG TY TRÁCH NHIỆM HỮU HẠN TÂN HÀ SÁNG,8.0,1.0,8737.0,14100.0,NaN,58413.0,-3766.3,66.0,65.0
3,101063863.0,CÔNG TY TRÁCH NHIỆM HỮU HẠN HAI CHI,8.0,1.0,1873.0,13920.0,NaN,1873.0,4.4,7.0,7.0
4,101070772.0,DOANH NGHIỆP TƯ NHÂN NHÂN SẢN XUẤT VÀ THƯƠNG M...,6.0,1.0,1149.0,16292.0,NaN,1436.0,12.4,5.0,5.0

In [ ]:
df_2019_core['Masothue'].dtype

dtype('float64')

In [ ]:
df_2019_core['Masothue']=df_2019_core['Masothue'].astype('int').astype('string')
df_2019_core['Masothue'].dtype

string[python]

In [ ]:
df_2019_core.value_counts('LoaihinhKT').sort_index()

LoaihinhKT
1.0        366
2.0        494
3.0       1153
4.0        114
5.0      14291
6.0      40950
7.0       1179
8.0     481434
9.0     129650
10.0      1212
11.0     15964
12.0       288
13.0      2155
Name: count, dtype: int64

In [ ]:
df_2019_core['MaTinh_Dieutra'].dtype

dtype('float64')

In [ ]:
df_2019_core['MaTinh_Dieutra'].astype('int').astype('string')

1          1
2          1
3          1
4          1
5          1
          ..
689246    96
689247    96
689248    96
689249    96
689250    96
Name: MaTinh_Dieutra, Length: 689250, dtype: string

In [ ]:
df_2019_core['MaTinh_Dieutra'].value_counts(dropna=False).sort_index()

MaTinh_Dieutra
1.0     141980
2.0       1054
4.0        989
6.0        630
8.0       1375
         ...
92.0      8123
93.0      1821
94.0      2330
95.0      1931
96.0      3418
Name: count, Length: 63, dtype: int64

In [ ]:
df_2019_core['SoLaodong_CuoiNam'].dtype

dtype('float64')

In [ ]:
df_2019_core['SoLaodong_CuoiNam'].isna().sum()

np.int64(0)

Check revenue, profit and employment for impossible or suspicious values (for example negativeemployment or implausible zeros).

In [ ]:
cols_check = [
    'TongDoanhthu_DTDN',
    'Doanhthu_Nganh',
    'Loinhuan_SauThue',
    'SoLaodong_CuoiNam'
]

In [ ]:
df_2019_core[cols_check].describe()

       TongDoanhthu_DTDN  Doanhthu_Nganh  Loinhuan_SauThue  SoLaodong_CuoiNam
count       1.178670e+05    6.892500e+05      6.892490e+05      689250.000000
mean        1.518712e+05    3.404644e+04     -7.516129e+02          21.246253
std         2.897129e+06    1.159932e+06      1.097796e+06         265.712561
min         0.000000e+00   -2.406915e+05     -8.894607e+08           1.000000
25%         1.073000e+03    6.400000e+01     -3.530000e+01           2.000000
50%         6.674400e+03    1.303300e+03      0.000000e+00           4.000000
75%         3.749850e+04    7.416975e+03      2.130000e+01           9.000000
max         6.550082e+08    6.539492e+08      4.608261e+07       63958.000000

In [ ]:
for col in cols_check:
    print(f'\n--- {col} ---')
    print('Missing:', df_2019_core[col].isna().sum())
    print('Zero:', (df_2019_core[col] == 0).sum())
    print('Negative:', (df_2019_core[col] < 0).sum())
    print('Minimum:', df_2019_core[col].min())
    print('Maximum:', df_2019_core[col].max())

--- TongDoanhthu_DTDN ---
Missing: 571383
Zero: 1182
Negative: 0
Minimum: 0.0
Maximum: 655008211.0

--- Doanhthu_Nganh ---
Missing: 0
Zero: 137578
Negative: 135
Minimum: -240691.5
Maximum: 653949195.0

--- Loinhuan_SauThue ---
Missing: 1
Zero: 120363
Negative: 299614
Minimum: -889460688.4
Maximum: 46082609.8

--- SoLaodong_CuoiNam ---
Missing: 0
Zero: 0
Negative: 0
Minimum: 1.0
Maximum: 63958.0

In [ ]:
negative_emp=df_2019_core[df_2019_core['SoLaodong_CuoiNam']<0]

In [ ]:
negative_emp.head()

Empty DataFrame
Columns: [Masothue, TenDN, LoaihinhKT, MaTinh_Dieutra, Doanhthu_Nganh, MaNganhSXKD_Chinh, Doanhthu_BH_CCDV, TongDoanhthu_DTDN, Loinhuan_SauThue, SoLaodong_CuoiNam, SoLaodong_BQ]
Index: []

In [ ]:
loss_firms = df_2019_core[df_2019_core['Loinhuan_SauThue'] < 0]
loss_firms.head()

print('Number of loss-making firms:', len(loss_firms))

Number of loss-making firms: 299614

In [ ]:
loss_firms.head()

,Masothue,TenDN,LoaihinhKT,MaTinh_Dieutra,Doanhthu_Nganh,MaNganhSXKD_Chinh,Doanhthu_BH_CCDV,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ
2,100998568,CÔNG TY TRÁCH NHIỆM HỮU HẠN TÂN HÀ SÁNG,8.0,1.0,8737.0,14100.0,NaN,58413.0,-3766.3,66.0,65.0
8,101300899,CÔNG TY CỔ PHẦN XÂY DỰNG VÀ THƯƠNG MẠI VIỆT HOÀNG,9.0,1.0,56038.0,5100.0,NaN,56038.0,-91.3,76.0,76.0
13,101507727,CÔNG TY TRÁCH NHIỆM HỮU HẠN THƯƠNG MẠI SẢN XUẤ...,8.0,1.0,81981.0,46499.0,NaN,81981.0,-119.8,23.0,20.0
17,101653686,CÔNG TY TRÁCH NHIỆM HỮU HẠN THƯƠNG MẠI TỔNG HỢ...,8.0,1.0,549.0,55103.0,NaN,1118.0,-1853.4,17.0,17.0
19,101861333,CÔNG TY TRÁCH NHIỆM HỮU HẠN SẢN XUẤT VÀ THƯƠNG...,8.0,1.0,11717.0,22209.0,NaN,11717.0,-931.8,4.0,4.0

In [ ]:
zero_revenue_nonzero_profit = df_2019_core[(df_2019_core['TongDoanhthu_DTDN'] == 0) & (df_2019_core['Loinhuan_SauThue'] != 0)]

zero_revenue_nonzero_profit[
    ['Masothue',
     'TenDN',
     'TongDoanhthu_DTDN',
     'Loinhuan_SauThue']].head(20)

,Masothue,TenDN,TongDoanhthu_DTDN,Loinhuan_SauThue
87,100113448,CHI NHÁNH DS AVOCATS TẠI HÀ NỘI,0.0,-138.6
149,106175320,CÔNG TY TRÁCH NHIỆM HỮU HẠN CAREGO (VIỆT NAM),0.0,-29.2
236,102743300,CÔNG TY CỔ PHẦN VINAFACADE,0.0,-516.9
249,104264409,CÔNG TY CỔ PHẦN VIGLACERA DETA,0.0,-311.9
319,305400669,CÔNG TY TRÁCH NHIỆM HỮU HẠN CÔNG TRÌNH ĐỊA CHẤ...,0.0,-470.5
445,106569734,CÔNG TY TNHH BKT VIỆT NAM,0.0,-644.1
461,106901533,CÔNG TY TRÁCH NHIỆM HỮU HẠN VIETDUTCH PROPERTY,0.0,-3416.2
478,107406482,CÔNG TY TRÁCH NHIỆM HỮU HẠN MORIKOU VIỆT NAM,0.0,14.7
488,107645480,CỤNG TY TNHH LOTTE PROPERTIES HÀ NỘI,0.0,-37710.6
509,108193607,CÔNG TY TNHH NICE TECH CENTER VIỆT NAM,0.0,-15500.1
517,108420088,CÔNG TY CỔ PHẦN O'S&TEC VIỆT NAM,0.0,-2493.8
518,108519961,CÔNG TY TNHH DỊCH VỤ A&T IRYO VIỆT NAM,0.0,-811.0
522,108669766,CÔNG TY TNHH MÔ HÌNH NHÀ HÀNG MODERN,0.0,-3.6
523,108713694,CÔNG TY CỔ PHẦN TƯ VẤN MOS VIỆT NAM,0.0,-3068.0
525,108867630,CÔNG TY TNHH WE MAKE VIỆT NAM,0.0,-528.1
789,108682929,CÔNG TY TNHH HAWSIN ENGINEERING VIỆT NAM,0.0,-85.6
955,107347935,CÔNG TY TNHH MỘT THÀNH VIÊN TWENTYCI VIỆT NAM,0.0,-4262.5
1019,105825512,CÔNG TY TNHH QUẢN LÝ KHÁCH SẠN CANDEO HÀ NỘI,0.0,-108.1
1032,106227378,CÔNG TY TRÁCH NHIỆM HỮU HẠN KỸ THUẬT SỐ MỞ RỘNG,0.0,-146.9
1069,100109603,CÔNG TY CỔ PHẦN ĐIỆN TỬ GIẢNG VÕ,0.0,-1109.9

In [ ]:
variables=[ 'TongDoanhthu_DTDN',
    'Doanhthu_Nganh',
    'Loinhuan_SauThue',
    'SoLaodong_CuoiNam']

In [ ]:
for col in variables: 
    q99=df_2019_core[col].quantile(0.99)
    print(f'{col}:')
    print('99th percentile:', q99)
    print('number above...:',(df_2019_core[col]>q99).sum())

TongDoanhthu_DTDN:
99th percentile: 2137007.0339999986
number above...: 1179
Doanhthu_Nganh:
99th percentile: 427476.91800000076
number above...: 6893
Loinhuan_SauThue:
99th percentile: 9998.22400000007
number above...: 6893
SoLaodong_CuoiNam:
99th percentile: 270.0
number above...: 6891

In [ ]:
summary = df_2019_core[variables].agg(
    ['count', 'mean', 'median', 'std', 'min', 'max']
)

summary

        TongDoanhthu_DTDN  Doanhthu_Nganh  Loinhuan_SauThue  SoLaodong_CuoiNam
count        1.178670e+05    6.892500e+05      6.892490e+05      689250.000000
mean         1.518712e+05    3.404644e+04     -7.516129e+02          21.246253
median       6.674400e+03    1.303300e+03      0.000000e+00           4.000000
std          2.897129e+06    1.159932e+06      1.097796e+06         265.712561
min          0.000000e+00   -2.406915e+05     -8.894607e+08           1.000000
max          6.550082e+08    6.539492e+08      4.608261e+07       63958.000000

In [ ]:
df_2019_core['Revenue_per_worker'] = (
    df_2019_core['Doanhthu_Nganh'] /
    df_2019_core['SoLaodong_CuoiNam'].replace(0, np.nan)
)

df_2019_core['Profit_per_worker'] = (
    df_2019_core['Loinhuan_SauThue'] /
    df_2019_core['SoLaodong_CuoiNam'].replace(0, np.nan)
)

df_2019_core['Profit_margin'] = (
    df_2019_core['Loinhuan_SauThue'] /
    df_2019_core['Doanhthu_Nganh'].replace(0, np.nan)
)

In [ ]:
summary_type = (
    df_2019_core
    .groupby('LoaihinhKT')
    .agg(
        Number_of_firms=('Masothue', 'nunique'),
        Avg_revenue=('Doanhthu_Nganh', 'mean'),
        Median_revenue=('Doanhthu_Nganh', 'median'),
        Avg_profit=('Loinhuan_SauThue', 'mean'),
        Median_profit=('Loinhuan_SauThue', 'median'),
        Avg_employment=('SoLaodong_CuoiNam', 'mean'),
        Total_employment=('SoLaodong_CuoiNam', 'sum'),
        Avg_revenue_per_worker=('Revenue_per_worker', 'mean')
    )
)
summary_type

,Number_of_firms,Avg_revenue,Median_revenue,Avg_profit,Median_profit,Avg_employment,Total_employment,Avg_revenue_per_worker
LoaihinhKT,,,,,,,,
1.0,354,2.364910e+06,109831.500,20980.463288,203.20,720.901639,263850.0,3015.394507
2.0,491,4.479136e+05,30086.500,34256.336235,237.40,227.127530,112201.0,16540.944122
3.0,1139,7.818111e+05,82287.000,32348.860711,1177.60,301.380746,347492.0,3812.958955
4.0,89,2.183818e+06,30858.745,47589.004386,0.00,714.605263,81465.0,2108.022616
5.0,14287,7.566033e+03,1089.000,198.196081,0.00,12.742985,182110.0,524.160198
6.0,40946,9.498585e+03,1569.660,13.574274,0.00,7.459634,305472.0,1545.259276
7.0,1179,2.755905e+03,554.400,93.164461,0.00,6.653096,7844.0,373.769833
8.0,481280,1.587561e+04,1105.650,-1780.767099,0.00,10.211805,4916310.0,2332.154998
9.0,129560,4.232231e+04,1633.400,822.740795,0.00,25.035079,3245798.0,2791.500840
10.0,1210,4.067635e+05,50642.500,27640.955941,636.65,209.786304,254261.0,3756.286067
11.0,15927,3.809957e+05,26071.520,4849.896223,0.00,285.897770,4564072.0,2907.962423
12.0,288,1.835568e+06,79423.500,112209.878125,565.10,261.649306,75355.0,7235.674806
13.0,2154,2.296766e+05,14011.000,8613.456659,0.00,133.526682,287750.0,3012.831357

How do revenue, profit, employment, and labor productivity differ among state-owned, domestic non-state, and foreign-invested enterprises?

In [ ]:
df_2019_core['LoaihinhKT'] = pd.to_numeric(
    df_2019_core['LoaihinhKT'],
    errors='coerce'
)

In [ ]:
def classify_ownership(x):
    if 1 <= x <= 4:
        return 'State-owned'
    elif 5 <= x <= 10:
        return 'Domestic non-state'
    elif 11 <= x <= 13:
        return 'Foreign-invested'
    else:
        return 'Unknown'

In [ ]:
# Create a new variable
df_2019_core['Ownership_group'] = (
    df_2019_core['LoaihinhKT']
    .apply(classify_ownership)
)

In [ ]:
df_2019_core['Ownership_group'].value_counts()

Ownership_group
Domestic non-state    668716
Foreign-invested       18407
State-owned             2127
Name: count, dtype: int64

In [ ]:
df_2019_core.groupby('Ownership_group').agg(
    Avg_revenue=('Doanhthu_Nganh', 'mean'),
    Avg_profit=('Loinhuan_SauThue', 'mean'),
    Avg_employment=('SoLaodong_CuoiNam', 'mean')
)

                     Avg_revenue    Avg_profit  Avg_employment
Ownership_group
Domestic non-state  2.112031e+04  -1067.201199       13.326726
Foreign-invested    3.860386e+05   6970.293220      267.679524
State-owned         1.051815e+06  31657.517451      378.471086

In [ ]:
Use groupby().transform() to calculate the average revenue within each ownership group.
Create a new variable indicating whether each enterprise has revenue above or below its group average.

In [ ]:
# Calculate the average revenue for each ownership group
df_2019_core['Group_avg_revenue'] = (
    df_2019_core
    .groupby('Ownership_group')['Doanhthu_Nganh']
    .transform('mean')
)

df_2019_core

,Masothue,TenDN,LoaihinhKT,MaTinh_Dieutra,Doanhthu_Nganh,MaNganhSXKD_Chinh,Doanhthu_BH_CCDV,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ,Revenue_per_worker,Profit_per_worker,Profit_margin,Ownership_group,Group_avg_revenue
1,100512361,CÔNG TY TRÁCH NHIỆM HỮU HẠN THƯƠNG MẠI VÀ BAO ...,8.0,1.0,59577.00,22201.0,NaN,59577.0,150.2,30.0,31.0,1985.900000,5.006667,0.002521,Domestic non-state,21120.305494
2,100998568,CÔNG TY TRÁCH NHIỆM HỮU HẠN TÂN HÀ SÁNG,8.0,1.0,8737.00,14100.0,NaN,58413.0,-3766.3,66.0,65.0,132.378788,-57.065152,-0.431075,Domestic non-state,21120.305494
3,101063863,CÔNG TY TRÁCH NHIỆM HỮU HẠN HAI CHI,8.0,1.0,1873.00,13920.0,NaN,1873.0,4.4,7.0,7.0,267.571429,0.628571,0.002349,Domestic non-state,21120.305494
4,101070772,DOANH NGHIỆP TƯ NHÂN NHÂN SẢN XUẤT VÀ THƯƠNG M...,6.0,1.0,1149.00,16292.0,NaN,1436.0,12.4,5.0,5.0,229.800000,2.480000,0.010792,Domestic non-state,21120.305494
5,101233353,CÔNG TY TRÁCH NHIỆM HỮU HẠN BAO BÌ VÀ THƯƠNG M...,8.0,1.0,24693.00,17021.0,NaN,39221.0,216.2,68.0,66.0,363.132353,3.179412,0.008756,Domestic non-state,21120.305494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689246,2000412060,doanh nghiệp tư nhân lương thanh nhuận,6.0,96.0,0.00,47300.0,NaN,NaN,0.0,5.0,5.0,0.000000,0.000000,NaN,Domestic non-state,21120.305494
689247,2001109814,doanh nghiệp tư nhân phượng hôn,6.0,96.0,242473.14,46322.0,NaN,NaN,0.0,6.0,6.0,40412.190000,0.000000,0.000000,Domestic non-state,21120.305494
689248,2001158586,doanh nghiệp tư nhân kim ngọc,6.0,96.0,0.00,47732.0,NaN,NaN,0.0,3.0,3.0,0.000000,0.000000,NaN,Domestic non-state,21120.305494
689249,2000237531,doanh nghiệp tư nhân chí tâm ii,6.0,96.0,1167.30,35302.0,NaN,NaN,-63.0,3.0,3.0,389.100000,-21.000000,-0.053971,Domestic non-state,21120.305494
689250,2001004829,công ty trách nhiệm hữu hạn mtv xd nguyễn dũng,8.0,96.0,6026.95,47739.0,NaN,NaN,0.0,5.0,5.0,1205.390000,0.000000,0.000000,Domestic non-state,21120.305494

In [ ]:
# Compare each firm's revenue with the average revenue of its ownership group
df_2019_core['Above_group_avg_revenue'] = (
    df_2019_core['Doanhthu_Nganh']
    > df_2019_core['Group_avg_revenue']
)

In [ ]:
df_2019_core['Above_group_avg_revenue'].astype(int)

1         1
2         0
3         0
4         0
5         1
         ..
689246    0
689247    1
689248    0
689249    0
689250    0
Name: Above_group_avg_revenue, Length: 689250, dtype: int64

In [ ]:
# Calculate the difference between firm revenue
# and the average revenue of its ownership group
df_2019_core['Revenue_gap'] = (
    df_2019_core['Doanhthu_Nganh']
    - df_2019_core['Group_avg_revenue']
)

Standardize enterprise names to reduce inconsistencies caused by extra spaces and different capitalization.

In [ ]:
df_2019_core['TenDN_clean'] = (
    df_2019_core['TenDN']
    .str.strip()
    .str.upper()
    .str.replace(r'\s+', ' ', regex=True)
)

In [ ]:
vin_firms = df_2019_core[
    df_2019_core['TenDN_clean']
    .str.contains('VIN', na=False)
]

vin_firms.head()

,Masothue,TenDN,LoaihinhKT,MaTinh_Dieutra,Doanhthu_Nganh,MaNganhSXKD_Chinh,Doanhthu_BH_CCDV,TongDoanhthu_DTDN,Loinhuan_SauThue,SoLaodong_CuoiNam,SoLaodong_BQ,Revenue_per_worker,Profit_per_worker,Profit_margin,Ownership_group,Group_avg_revenue,Above_group_avg_revenue,Revenue_gap,TenDN_clean
35,103619553,CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ XÂY DỰNG ĐĂNG VINH,9.0,1.0,9762.00,42120.0,NaN,9762.00,111.2,28.0,28.0,348.642857,3.971429,0.011391,Domestic non-state,21120.305494,False,-11358.305494,CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ XÂY DỰNG ĐĂNG VINH
41,104939098,CÔNG TY TRÁCH NHIỆM HỮU HẠN MÁY HÀN VINABEST,11.0,1.0,7255.03,46599.0,NaN,7255.03,925.1,4.0,4.0,1813.757500,231.275000,0.127512,Foreign-invested,386038.553557,False,-378783.523557,CÔNG TY TRÁCH NHIỆM HỮU HẠN MÁY HÀN VINABEST
231,102625829,CÔNG TY TRÁCH NHIỆM HỮU HẠN VINACOMPOUND,8.0,1.0,713086.00,22209.0,NaN,811371.00,410.0,144.0,130.0,4951.986111,2.847222,0.000575,Domestic non-state,21120.305494,True,691965.694506,CÔNG TY TRÁCH NHIỆM HỮU HẠN VINACOMPOUND
236,102743300,CÔNG TY CỔ PHẦN VINAFACADE,12.0,1.0,0.00,43300.0,NaN,0.00,-516.9,3.0,3.0,0.000000,-172.300000,NaN,Foreign-invested,386038.553557,False,-386038.553557,CÔNG TY CỔ PHẦN VINAFACADE
296,106848287,CÔNG TY TNHH ABIVIN VIỆT NAM,11.0,1.0,4367.40,46510.0,NaN,4367.40,-4751.3,54.0,35.0,80.877778,-87.987037,-1.087901,Foreign-invested,386038.553557,False,-381671.153557,CÔNG TY TNHH ABIVIN VIỆT NAM

In [ ]:
vingroup_keywords = [
    'VINGROUP',
    'VINFAST',
    'VINHOMES',
    'VINCOM',
    'VINPEARL',
    'VINMEC',
    'VINSCHOOL',
    'VINSMART'
]

In [ ]:
pattern = '|'.join(vingroup_keywords)

vingroup_firms = df_2019_core[
    df_2019_core['TenDN_clean']
    .str.contains(pattern, na=False, regex=True)
]

vingroup_firms[['Masothue', 'TenDN']].head(30)

          Masothue                                              TenDN
3909     101245486                TẬP ĐOÀN VINGROUP - CÔNG TY CỔ PHẦN
3936     105850244                      CÔNG TY CỔ PHẦN VINCOM RETAIL
3945     106156871  CÔNG TY TRÁCH NHIỆM HỮU HẠN MỘT THÀNH VIÊN VIN...
3948     106339402  CÔNG TY TRÁCH NHIỆM HỮU HẠN DỊCH VỤ BẢO VỆ VINCOM
10826    106050554   CÔNG TY CỔ PHẦN BỆNH VIỆN ĐA KHOA QUỐC TẾ VINMEC
12709    106250673               CÔNG TY TNHH  VINCOM RETAIL MIỀN BẮC
19291    108321672    CÔNG TY CỔ PHẦN NGHIÊN CỨU VÀ SẢN XUẤT VINSMART
33238   2500492709  CÔNG TY CỔ PHẦN TƯ VẤN ĐẦU TƯ XÂY DỰNG VINCOM(...
39713    201968506          CÔNG TY TNHH SẢN XUẤT PIN LITHIUM VINFAST
41235    107894416        CÔNG TY TNHH SẢN XUẤT VÀ KINH DOANH VINFAST
64042   4200456848                           CÔNG TY CỔ PHẦN VINPEARL
84753    104918404     CTY CP DỊCH VỤ THƯƠNG MẠI TỔNG HỢP VINCOMMERCE
120839   101959829  Công Ty Trách Nhiệm Hữu Hạn Tư Vấn Và Xây Dựng...
133013   106012132                          CÔNG TY CỔ PHẦN SLOVINCOM
136114   107734042  CôNG TY Cổ PHầN Tư VấN ĐầU Tư Và PHáT TRIểN Cô...
146578   108543629                  Công Ty Cổ PHầN VINGROUP VENTURES
147728   108465787         Công Ty TNHH DịCH Vụ Và KINH DOANH VINFAST
147799   108712524            CÔNG TY CỔ PHẦN HÀNG KHÔNG VINPEARL AIR
149678   108750463          Công Ty TNHH XÂY LắP Và THƯƠNG MạI VINMEC
171024   107707017                    CôNG TY Cổ PHầN VINSMART TRAVEL
193073   105794416            CÔNG TY CỔ PHẦN XUẤT NHẬP KHẨU VINGROUP
202436   106569639                             CÔNG TY TNHH SINVINCOM
222291   108124755  CÔNG TY TNHH VỆ SINH CÔNG NGHIỆP THẾ GIỚI SẠCH...
226645   108287830                CôNG TY Cổ PHầN SơN VINMEC VIệT NAM
270065  2301058180                      CôNG TY Cổ PHầN Cơ KHí VINMEC
293193   201914211   CôNG TY TNHH LINH KIệN NHựA ô Tô VINFAST-AN PHáT
293586   201932411         CôNG TY TNHH LINH KIệN ô Tô AAPICO VINFAST
297491   901017175  CÔNG TY TNHH THƯƠNG MẠI VÀ DINH DƯỠNG VINCOM FEED
312211  2801729912            CôNG TY TNHH Tư VấN Và XâY DựNG GVINCOM
314109  2801832250    Công Ty Cổ Phần Xây Dựng Và Thương Mại Vincomat

In [ ]:
vingroup_firms_new = df_2019_core[
    df_2019_core['TenDN_clean']
    .str.contains(r'VINFAT|VINHOMES', na=False, regex=True)
]